export const Images = {
  oceanBackground: require('./ocean_background.png'),
  sharkMascot: require('./shark_mascot.png'),
  onboardingStories: require('./onboarding_stories.png'),
  onboardingMap: require('./onboarding_map.png'),
  onboardingSaved: require('./onboarding_saved.png'),
  locationTigerBeach: require('./tiger_beach.png'),
  locationGansbaai: require('./gansbaai.png'),
  locationIslaGuadalupe: require('./isla_guadalupe.png'),
  locationNeptuneIslands: require('./neptune_islands.png'),
  locationBeqaLagoon: require('./beqa_lagoon.png'),
  locationCocosIsland: require('./cocos_island.png'),
  locationMalpeloIsland: require('./malpelo_island.png'),
  locationSocorroIsland: require('./socorro_island.png'),
  locationRangiroa: require('./rangiroa.png'),
  locationFuvahmulah: require('./fuvahmulah.png'),
  locationOspreyReef: require('./osprey_reef.png'),
  locationAliwalShoal: require('./aliwal_shoal.png'),
  locationBimini: require('./bimini.png'),
  locationNingalooReef: require('./ningaloo_reef.png'),
  locationDarwinIsland: require('./darwin_island.png'),
};
